name: Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Connect to server using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            sudo chmod 777 /var/run/docker.sock
            cd /home/aqzaqz/project/hidden-gem-backend
            git pull origin main
            docker stop hidden_gem_container
            docker rm  hidden_gem_container
            docker rmi hidden_gem_images:latest
            docker build -t hidden_gem_images:latest .
            docker run -d \
            -p 5000:5000 \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e TEST_DB_USER=${{ secrets.TEST_DB_USER }} \
            -e TEST_DB_PASSWORD= ${{ secrets.TEST_DB_PASSWORD }} \
            -e DEBUG=${{ secrets.DEBUG }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
            -e REDIS_PORT=${{ secrets.REDIS_PORT }} \
            -e REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
            --name hidden_gem_container \
            hidden_gem_images:latest
