name: Flask Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DEFAULT_DB_NAME: ${{ secrets.DEFAULT_DB_NAME }}
      TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}

    steps:
    - name: Print Environment Variables
        run: |
          echo "DEFAULT_DB_NAME=${DEFAULT_DB_NAME}"
          echo "TEST_DB_NAME=${TEST_DB_NAME}"
          echo "DEBUG=${DEBUG}"
          echo "DB_PORT=${DB_PORT}"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask tests
      run: |
        flask test
